# Design-Aware Population Conformal Bands — pure-R port of the reference
# Python implementation (pcb.dapcb). Numerical agreement with the Python
# package is enforced by the golden tests under tests/ (cases generated by the
# Python reference; tolerance 1e-10). All safe-selector constants are FROZEN
# (SAFE_SELECTOR_SPEC.md in the replication package) and not user-tunable.

# --- frozen safe-selector constants ------------------------------------------
.RHO0        <- 0.47        # gate A: SD-ratio cutoff
.DELTA_MAX   <- 0.02        # gate B: coverage-remainder budget
.DUCB_A      <- 0.0061      # gate B: delta_ucb(D) = a + b*D
.DUCB_B      <- 0.0943
.G_MIN       <- 0.10        # gate C: minimum width gain over conservative
.GAIN_MARGIN <- 0.05        # gate C: frozen conservative LCB margin
.Z           <- 1.6448536   # one-sided guard constant
.BUDGET_DEC  <- 0.10        # fraction of alpha reserved for deconvolution

# numpy-compatible population SD (ddof = 0), columnwise
.colsd0 <- function(M) {
  mu <- colMeans(M)
  sqrt(colMeans(sweep(M, 2, mu)^2))
}

#' Frozen upper bound on the finite-K deconvolution coverage remainder
#' @param D reliability diagnostic (see [deconv_reliability()])
#' @return numeric scalar
#' @export
delta_ucb <- function(D) .DUCB_A + .DUCB_B * as.numeric(D)

#' Can gate B open at all at this K? (deterministic reliability floor)
#'
#' The diagnostic obeys D >= sqrt(2/(K-1)) identically, so if
#' delta_ucb(sqrt(2/(K-1))) already exceeds the budget, no dataset can open
#' gate B (the K >= 94 floor of the companion paper's Proposition 1).
#' @param K number of calibration populations
#' @return logical
#' @export
gate_b_feasible <- function(K) {
  floor_ <- sqrt(2 / max(K - 1, 1))
  delta_ucb(floor_) <= .DELTA_MAX
}

#' Frozen (alpha_anchor, alpha_dec) split of the miscoverage budget
#' @param K number of calibration populations
#' @param alpha total miscoverage level
#' @return numeric length-2 vector c(alpha_anchor, alpha_dec)
#' @export
alpha_split <- function(K, alpha) {
  if (!gate_b_feasible(K)) return(c(alpha, 0))
  a_dec <- min(max(.BUDGET_DEC * alpha, 3 / (K + 1)), 0.5 * alpha)
  c(alpha - a_dec, a_dec)
}

# pointwise spread of the transport error, floored (numpy std ddof=0)
.modulation <- function(E, floor_frac = 0.05) {
  s <- .colsd0(E)
  pmax(s, floor_frac * max(max(s), 1e-12))
}

#' Finite-K-safe deconvolved target scale
#'
#' Guards the mean(v^2) subtraction with its one-sided lower confidence bound,
#' so the correction subtracts less when the design-noise estimate is
#' uncertain; never exceeds the plug-in scale.
#' @param cal_errors K x T matrix of transport-error curves
#' @param v_cal K x T matrix of design-noise SDs
#' @param z guard constant (frozen default)
#' @param floor_frac scale floor fraction
#' @return numeric length-T vector
#' @export
deconv_target_scale <- function(cal_errors, v_cal, z = .Z, floor_frac = 0.05) {
  E <- as.matrix(cal_errors); V <- as.matrix(v_cal)
  K <- nrow(E)
  s_plug <- .modulation(E, floor_frac)
  mv <- colMeans(V^2)
  se <- .colsd0(V^2) / sqrt(max(K, 1))
  sub <- pmax(mv - z * se, 0)
  floor_ <- (floor_frac * max(s_plug))^2
  sqrt(pmax(s_plug^2 - sub, floor_))
}

#' One-sided lower confidence bound on rho = design-SD / total-SD
#' @inheritParams deconv_target_scale
#' @return numeric scalar in [0, 1)
#' @export
rho_lcb <- function(cal_errors, v_cal, z = .Z, floor_frac = 0.05) {
  E <- as.matrix(cal_errors); V <- as.matrix(v_cal)
  K <- nrow(E)
  s_plug <- .modulation(E, floor_frac)
  mv <- colMeans(V^2)
  se <- .colsd0(V^2) / sqrt(max(K, 1))
  num <- mean(pmax(mv - z * se, 0))
  den <- mean(s_plug^2 * (1 + z * sqrt(2 / max(K - 1, 1))))
  if (den > 0) sqrt(num / den) else 0
}

#' Finite-K reliability diagnostic D
#'
#' D = max_t SE(s_T_safe^2) / s_T_safe^2; large D means the deconvolved scale
#' is poorly determined and the deconvolution is unsafe at this K.
#' @inheritParams deconv_target_scale
#' @return numeric scalar
#' @export
deconv_reliability <- function(cal_errors, v_cal, floor_frac = 0.05) {
  E <- as.matrix(cal_errors); V <- as.matrix(v_cal)
  K <- nrow(E)
  s_plug <- .modulation(E, floor_frac)
  sT2 <- deconv_target_scale(E, V, floor_frac = floor_frac)^2
  se_sT2 <- sqrt(2 * s_plug^4 / max(K - 1, 1) + (.colsd0(V^2) / sqrt(K))^2)
  max(se_sT2 / pmax(sT2, 1e-12))
}

# conformal order-statistic quantile; Inf when the level exceeds K
.finite_quantile <- function(scores, alpha) {
  K <- length(scores)
  idx <- ceiling((1 - alpha) * (K + 1))
  if (idx > K) Inf else sort(scores)[idx]
}

#' Coverage-preserving isotonic tightening of a CDF band
#'
#' The truth is a nondecreasing [0,1] function, so the lower bound may be
#' raised to its running maximum and the upper bound lowered to its running
#' minimum from the right without losing coverage.
#' @param lo,hi numeric vectors (band limits over the threshold grid)
#' @return list(lo, hi)
#' @export
isotonic_tighten <- function(lo, hi) {
  lo <- pmin(pmax(cummax(lo), 0), 1)
  hi <- pmin(pmax(rev(cummin(rev(hi))), 0), 1)
  list(lo = lo, hi = pmax(hi, lo))
}

#' Design-aware population conformal band (nominal-safe adaptive selector)
#'
#' One call: transport-error curves of K source populations, each with a
#' design-noise estimate from a complex-survey bootstrap, in; a simultaneous
#' band for a new population's curve out. Deconvolution is used only when four
#' target-blind gates certify it is reliable at this K; otherwise the method
#' reduces to the exact clustered band (low design noise) or a conservative
#' envelope. The deployed guarantee is exact 1 - alpha for the SURVEY-ESTIMATE
#' trajectory (T1) whenever the deconvolution branch is unreachable (K < 94 at
#' the frozen constants) -- in the default leave-one-out centering this holds
#' for the construction as shipped, via the K/(K-1) anchor-radius inflation of
#' the LOO-validity proposition (see \code{loo_center}); coverage of the latent trajectory then differs by the
#' Theorem-2(b) design-noise gap, bounded through \code{rho_hat}. When the
#' branch is live (K >= 94) the reported 1 - alpha - delta_ucb(D) is a frozen
#' CALIBRATED bound on latent (T2) coverage, fit on the development grid and
#' validated on sealed runs -- not a theorem constant. The \code{target}
#' element of the result names which trajectory the level refers to.
#'
#' @param cal_errors K x T matrix: transport-error curves E_c(t) of the K
#'   source populations over a fixed T-threshold grid.
#' @param v_cal K x T matrix: design-noise SDs v_c(t) from a stratified-PSU /
#'   replicate-weight bootstrap; zeros for a census source.
#' @param center length-T vector: predicted curve for the new population.
#' @param alpha miscoverage level (default 0.10).
#' @param tighten apply the coverage-preserving isotonic tightening (default TRUE).
#' @param loo_center TRUE (default) declares the deployed construction:
#'   \code{cal_errors} were produced by leave-one-out centering around the
#'   pooled mean and \code{center} predicts an unsurveyed target. The returned
#'   anchor radii (PCB, conservative) then carry the K/(K-1) inflation of the
#'   LOO-validity proposition, restoring exact finite-sample validity for the
#'   construction as shipped; gates are evaluated on the uninflated radii
#'   (the frozen rule, unchanged). Set FALSE only for a symmetric center
#'   (fixed, own-unit, split-fold), which is exact uninflated. The
#'   deconvolution branch is never inflated (its guarantee is the frozen
#'   calibrated bound).
#' @return An object of class \code{dapcb}: a list with elements \code{lo},
#'   \code{hi}, \code{selected_branch}, \code{rho_hat}, \code{rho_lcb},
#'   \code{reliability}, \code{delta_ucb}, \code{gain_lcb},
#'   \code{coverage_level}, \code{target}, \code{fallback_reason},
#'   \code{overlap_warning}.
#' @examples
#' K <- 30; T_ <- 8
#' E <- matrix(rnorm(K * T_, 0, 0.05), K, T_)
#' V <- matrix(abs(rnorm(K * T_, 0.005, 0.001)), K, T_)
#' center <- pmin(cumsum(abs(rnorm(T_, 0.08, 0.02))), 1)
#' fit <- dapcb(E, V, center, alpha = 0.10)
#' print(fit)
#' @export
dapcb <- function(cal_errors, v_cal, center, alpha = 0.10, tighten = TRUE,
                  loo_center = TRUE) {
  E <- as.matrix(cal_errors); V <- as.matrix(v_cal)
  center <- as.numeric(center)
  if (!all(dim(V) == dim(E))) stop("cal_errors and v_cal must be (K, T) with equal shape")
  K <- nrow(E); T_ <- ncol(E)
  s  <- .modulation(E)
  sT <- deconv_target_scale(E, V)

  feasible <- gate_b_feasible(K)
  ab <- alpha_split(K, alpha)
  a_anchor <- ab[1]; a_dec <- ab[2]
  a_dec_q <- if (feasible) a_dec else alpha * .BUDGET_DEC

  q_pcb <- .finite_quantile(apply(abs(E), 1, max), a_anchor)
  q_dec <- .finite_quantile(
    apply(abs(E) / sqrt(matrix(sT^2, K, T_, byrow = TRUE) + V^2), 1, max), a_dec_q)
  q_con <- .finite_quantile(apply(abs(E) + .Z * V, 1, max), a_anchor)
  r_pcb <- rep(q_pcb, T_)
  r_con <- rep(q_con, T_)
  r_dec <- q_dec * sT

  rl <- rho_lcb(E, V)
  D  <- deconv_reliability(E, V)
  d_ucb <- delta_ucb(D)
  stable <- all(s^2 - colMeans(V^2) > (0.05 * max(s))^2)

  reason <- ""; gain_lcb <- NaN
  if (rl <= .RHO0) {
    branch <- "PCB"; radius <- r_pcb
    reason <- "design noise negligible (rho_LCB <= rho0) -> clustered PCB"
  } else {
    gate_b <- feasible && (d_ucb <= .DELTA_MAX)
    gate_d <- stable
    gate_c <- FALSE
    if (gate_b && gate_d) {
      w_dec <- mean(r_dec); w_con <- mean(r_con)
      gain_lcb <- (if (w_con > 0) 1 - w_dec / w_con else 0) - .GAIN_MARGIN
      gate_c <- gain_lcb > .G_MIN
    }
    if (gate_b && gate_d && gate_c) {
      branch <- "deconvolution"; radius <- r_dec
    } else {
      branch <- "conservative"; radius <- r_con
      reason <- paste0(
        if (!gate_b) "finite-K remainder too large (delta_UCB > delta_max)"
        else if (!gate_d) "deconvolution unstable"
        else "width gain insufficient (gain_LCB <= g_min)",
        " -> conservative fallback")
    }
  }
  cov <- 1 - alpha - (if (feasible) d_ucb else 0)
  target <- if (feasible) "latent (T2, calibrated bound)" else "survey-estimate (T1)"

  # deployed LOO centering: anchor radius inflated by K/(K-1) (LOO-validity
  # proposition); gates above decided on the uninflated radii (frozen rule)
  if (loo_center && branch != "deconvolution" && K >= 2)
    radius <- radius * K / (K - 1)

  lo <- center - radius; hi <- center + radius
  if (tighten) {
    th <- isotonic_tighten(pmin(pmax(lo, 0), 1), pmin(pmax(hi, 0), 1))
    lo <- th$lo; hi <- th$hi
  } else {
    lo <- pmin(pmax(lo, 0), 1); hi <- pmin(pmax(hi, 0), 1)
  }
  warn <- any(lo <= 0) && any(hi >= 1)
  structure(list(
    lo = lo, hi = hi, selected_branch = branch,
    rho_hat = sqrt(mean(V^2)) / mean(s), rho_lcb = rl, reliability = D,
    delta_ucb = d_ucb, gain_lcb = gain_lcb, coverage_level = cov,
    target = target, fallback_reason = reason, overlap_warning = warn),
    class = "dapcb")
}

#' @export
print.dapcb <- function(x, ...) {
  cat(sprintf(
    "dapcb: branch=%s, coverage>=%.3f [%s], mean width=%.3f\n  rho_hat=%.3f (LCB %.3f), D=%.3f, delta_UCB=%.3f%s\n",
    x$selected_branch, x$coverage_level, x$target, mean(x$hi - x$lo),
    x$rho_hat, x$rho_lcb, x$reliability, x$delta_ucb,
    if (!is.nan(x$gain_lcb)) sprintf(", gain_LCB=%.3f", x$gain_lcb) else ""))
  if (nzchar(x$fallback_reason)) cat("  fallback:", x$fallback_reason, "\n")
  if (x$overlap_warning) cat("  warning: band touches the [0,1] boundary\n")
  invisible(x)
}
