# Golden tests: the R port must reproduce the Python reference implementation
# to 1e-10 on seven cases spanning all three branches (PCB, conservative,
# deconvolution), a census source (V = 0), the K = 94 feasibility boundary,
# and a tiny-K edge case. Cases generated by
# rpkg/dapcb/inst/golden (from pcb.dapcb, the Python package in this repo).
# Base-R only: runs under R CMD check with no test dependencies.

library(dapcb)

golden <- system.file("golden", package = "dapcb")
if (golden == "") golden <- file.path("..", "inst", "golden")   # pre-install layout
cases <- list.dirs(golden, recursive = FALSE)
stopifnot(length(cases) >= 7)

# minimal JSON reader for the flat expected_meta.json files (base R only)
read_meta <- function(path) {
  txt <- paste(readLines(path, warn = FALSE), collapse = " ")
  txt <- gsub("[{}]", "", txt)
  parts <- strsplit(txt, ",(?=\\s*\")", perl = TRUE)[[1]]
  out <- list()
  for (p in parts) {
    kv <- strsplit(p, ":", fixed = TRUE)[[1]]
    key <- gsub('[" ]', "", kv[1])
    val <- trimws(paste(kv[-1], collapse = ":"))
    out[[key]] <-
      if (val %in% c("true", "false")) as.logical(toupper(val))
      else if (val == "null") NA_real_
      else if (grepl('^"', val)) gsub('"', "", val)
      else as.numeric(val)
  }
  out
}

tol <- 1e-10
for (d in cases) {
  name <- basename(d)
  E <- as.matrix(read.csv(file.path(d, "E.csv"), header = FALSE))
  V <- as.matrix(read.csv(file.path(d, "V.csv"), header = FALSE))
  center <- as.numeric(read.csv(file.path(d, "center.csv"), header = FALSE)[[1]])
  lo <- as.numeric(read.csv(file.path(d, "expected_lo.csv"), header = FALSE)[[1]])
  hi <- as.numeric(read.csv(file.path(d, "expected_hi.csv"), header = FALSE)[[1]])
  meta <- read_meta(file.path(d, "expected_meta.json"))

  fit <- dapcb(E, V, center, alpha = meta$alpha)

  stopifnot(
    identical(fit$selected_branch, meta$branch),
    max(abs(fit$lo - lo)) < tol,
    max(abs(fit$hi - hi)) < tol,
    abs(fit$rho_hat - meta$rho_hat) < tol,
    abs(fit$rho_lcb - meta$rho_lcb) < tol,
    abs(fit$reliability - meta$reliability) < tol,
    abs(fit$delta_ucb - meta$delta_ucb) < tol,
    abs(fit$coverage_level - meta$coverage_level) < tol,
    identical(fit$overlap_warning, meta$overlap_warning),
    if (is.na(meta$gain_lcb)) is.nan(fit$gain_lcb)
    else abs(fit$gain_lcb - meta$gain_lcb) < tol
  )
  cat(sprintf("golden OK: %-18s branch=%-13s cov=%.3f\n",
              name, fit$selected_branch, fit$coverage_level))
}
cat("all golden cases passed\n")
